Organizations:

  - &OrdererOrg
    Name: OrderingService
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/cit-network.com/msp
    
    Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

    OrdererEndpoints:
            - orderer.cit-network.com:7050

  - &cit1
    Name: cit1MSP
    ID: cit1MSP
    MSPDir: crypto-config/peerOrganizations/cit1.cit-network.com/msp
    Policies:
          Readers:
              Type: Signature
              Rule: "OR('cit1MSP.admin', 'cit1MSP.peer', 'cit1MSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('cit1MSP.admin', 'cit1MSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('cit1MSP.admin')" 
          Endorsement:
              Type: Signature
              Rule: "OR('cit1MSP.peer')"     

    AnchorPeers:
      - Host: peer0.cit1.cit-network.com
        Port: 7051

  - &cit2
    Name: cit2MSP
    ID: cit2MSP
    MSPDir: crypto-config/peerOrganizations/cit2.cit-network.com/msp
    Policies:
          Readers:
              Type: Signature
              Rule: "OR('cit2MSP.admin', 'cit2MSP.peer', 'cit2MSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('cit2MSP.admin', 'cit2MSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('cit2MSP.admin')" 
          Endorsement:
              Type: Signature
              Rule: "OR('cit2MSP.peer')" 

    AnchorPeers:
      - Host: peer0.cit2.cit-network.com
        Port: 7051

Capabilities:

    Channel: &ChannelCapabilities

        V2_0: true


    Orderer: &OrdererCapabilities
    
        V2_0: true

    Application: &ApplicationCapabilities

        V2_0: true
# Orderer

Orderer: &OrdererDefaults

    OrdererType: solo
    Addresses: 
        - orderer.cit-network.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Kafka:
        Brokers: 
            - 127.0.0.1:9092

    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
Channel: &ChannelDefaults

    Policies:

        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"

        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"


    Capabilities:
        <<: *ChannelCapabilities
# Application

Application: &ApplicationDefaults

    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"

    Capabilities:
        <<: *ApplicationCapabilities

Profiles:
    OrdererGenesis:
      <<: *ChannelDefaults
      Capabilities:
        <<: *ChannelCapabilities
      Orderer:
        <<: *OrdererDefaults
        Organizations:
          - *OrdererOrg
        Capabilities:
          <<: *OrdererCapabilities
      Consortiums:
        MyFirstConsortium:
          Organizations:
            - *cit1 
            - *cit2
            
    ChannelDemo:
      Consortium: MyFirstConsortium
      <<: *ChannelDefaults
      Application:
        <<: *ApplicationDefaults
        Organizations:
          - *cit1
          - *cit2
          
        Capabilities:
          <<: *ApplicationCapabilities